### PR TITLE
Add README.MD file and build

### PR DESCRIPTION
**Pull request by Persimmonboy**

### CODE REVIEW

**Comment by Persimmonboy** [comment]
recheck

**Comment by Persimmonboy** [comment]
recheck

**Comment by Persimmonboy** [comment]
recheck

**Comment by Persimmonboy** [comment]
recheck

**Comment by Persimmonboy** [comment]
recheck

**Comment by Persimmonboy** [comment]
recheck

**Review by anton-sidelnikov — APPROVED** [review]

**Review by artem-lifshits — DISMISSED** [review]

**Review by artem-lifshits — APPROVED** [review]

**Review by anton-sidelnikov — APPROVED** [review]

**Pull request merged**
